# Generated by Django 3.2.6 on 2021-08-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('artist', models.TextField()),
                ('track_id', models.TextField()),
                ('uri', models.TextField()),
                ('danceability', models.FloatField()),
                ('valence', models.FloatField()),
                ('energy', models.FloatField()),
                ('tempo', models.FloatField()),
                ('loudness', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('segments', models.FloatField()),
                ('tatums', models.FloatField()),
                ('bars', models.FloatField()),
                ('beats', models.FloatField()),
                ('pitches', models.FloatField()),
                ('timbre', models.FloatField()),
            ],
        ),
    ]
