# Generated by Django 3.2.6 on 2021-08-31 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='bars',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='beats',
            new_name='mode',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='pitches',
            new_name='time_signature',
        ),
        migrations.RemoveField(
            model_name='track',
            name='segments',
        ),
        migrations.RemoveField(
            model_name='track',
            name='tatums',
        ),
        migrations.RemoveField(
            model_name='track',
            name='timbre',
        ),
    ]
